### ISSUE TITLE
Bug Report: Error Installing Duplicate Finder App (v1.5.0) on Nextcloud Snapd 30. (Specified key was too long)

### ISSUE THREAD

**Issue by MasterKeks** [eldertek/duplicatefinder#112]
**Describe the bug**
Attempting to install the Duplicate Finder app (v1.5.0) on Nextcloud Hub 9 (30.0.4) fails with the following error:
```
An error occurred during the request. Unable to proceed.
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
```
The issue appears to be related to MariaDB’s default settings for key lengths in the Snap-managed environment.

**To Reproduce**
	1.	Open Nextcloud snapd version Hub 9 (30.0.4)
	2.	Navigate to the App Store.
	3.	Attempt to install the Duplicate Finder app (v1.5.0)
	4.	The installation fails with the above error.

**Expected behavior**
The Duplicate Finder app should install successfully without errors.

**Screenshots**
<img width="1268" alt="Error-Nextcloud-snapd" src="https://github.com/user-attachments/assets/a24d5635-4e1d-4d2d-a022-8c9c73b66fd1" />

**Versions**
	•	Nextcloud: Hub 9 (30.0.4) - snapd image
	•	Duplicate Finder: 1.5.0

**Additional context**
	•	The issue seems related to database settings (innodb_large_prefix, innodb_file_format, and innodb_default_row_format) in the Snap-managed MariaDB environment.
	•	Attempts to enable Snap experimental features and repair the database did not resolve the issue:
`sudo snap set nextcloud mysql.experimental-features=true
sudo nextcloud.occ maintenance:repair`
	•	Direct database access for configuration changes was not possible in Snap.

Any guidance or workaround would be appreciated!

Thanks.
Johannes

**Comment by eldertek** [comment]
Hello, fixed in v1.5.1 ;)

**Comment by MasterKeks** [comment]
> Hello, fixed in v1.5.1 ;)

Hey @eldertek,

Thanks for your fast response. Just updated everything to the newest version, but sadly still encounter the same issue, even with version 1.5.1:

<img width="1263" alt="Error-Nextcloud-snapd_1_5_1" src="https://github.com/user-attachments/assets/abe7d69a-42e3-4898-abe2-93e25841739b" />

I think its more related to settings in the nextcloud snapd package. But do you still have an idea to fix it?

Thanks.
Johannes

**Comment by eldertek** [comment]
Hi @MasterKeks,

Thanks for the update, and sorry to hear the issue persists with v1.5.1.

The error likely stems from MariaDB limitations in the Snap-managed environment (key length > 3072 bytes). Normally, this can be resolved by adjusting `innodb_large_prefix`, `innodb_file_format`, and `innodb_default_row_format`, but Snap restricts direct configuration.

### Suggested Steps:
1. Ensure both Nextcloud Snap (30.0.4) and MariaDB are fully updated.
2. Retry enabling experimental features and repairing:
   ```bash
   sudo snap set nextcloud mysql.experimental-features=true
   sudo nextcloud.occ maintenance:repair
   ```
3. Consider opening a discussion with the Snap or Nextcloud team, as this appears tied to Snap’s database limitations.

### Alternative:
If feasible, switch to a non-Snap Nextcloud installation for full control over MariaDB settings.

Let us know if you have more details—happy to assist further!

Best,  
Johannes

**Comment by Crell** [comment]
I am having this problem, too.  I've tried upgrading to 1.5.2 via manual download, and it still fails on upgrade.  I also tried manually downgrading to 1.4.1, and I'm still getting the same error!  As a result, my instance is offline and I am unclear how to resolve it.

I am on Ubuntu 24.04 with PHP 8.3 and MySQL 8.0.  I am not using any snaps.

It sounds like the suggestion is to "adjust" the MySQL settings, but I am not clear what they should be adjusted to...

**Comment by eldertek** [comment]
!log

**Comment by eldertek** [comment]
!log

**Comment by eldertek** [comment]
!log

**Comment by eldertek** [comment]
!log

**Comment by ASerbinski** [comment]
I'm getting this error also, for v1.5.2, NC30.0.2, Rocky Linux 8 / Apache 2.4.37 / PHP 8.2.26 / MariaDB 10.3.35.

I found that changing everything in this commit where it set lengths to 768 changing it to 700 seemed to fix the issue.
https://github.com/eldertek/duplicatefinder/commit/c638de2a2bbbe17fbc01ddd22e5fb522bff64d7e

**Comment by mickeyreg** [comment]
Hi,

The same problem on NC 28.0.14 / MySQL 8.0.39 / Apache 2.4.62 (FreeBSD) / PHP 8.2.24.

Following the advice of @ASerbinski I changed 768 to ... 704 and its working.

Why? I'm not sure, but parameters of my nextcloud database are as follows:

_nextcloud: utf8mb4_general_ci_

It means every character in string can be 4 bytes long.

So if the max index length is 3072 bytes, it is 768 characters: 64 for _**user_id**_ so the max for _**folder_path**_ id 704 - both fields are used in index.

Regards,
Mickey

**Comment by Crell** [comment]
I tried following @ASerbinski's approach on the 1.5.2 version, which meant I also had to modify the 1050 migration file the same way.  Once I did that, I was able to get the upgrade process to complete and unlock the server.

Does the 1.5.2 try to do something other than fix the field length to address this issue?  Should there be a 1.5.3 that shortens the fields down to 700?

**Comment by eldertek** [comment]
I just released version 1.5.3, which includes a hotfix for the migrations. Let me know if it works then

**Comment by mickeyreg** [comment]
Upgraded to 1.5.3 from manulay modified 1.5.2. No problems were noticed.

**Comment by Crell** [comment]
Upgrading to 1.5.3 gave me an error in the UI (non-specific, just "an error happened") and left the site in maintenance mode.  Switching to the CLI to run `occ upgrade` worked fine, though, and I was able to disable maintenance mode manually.  All seems well at the moment.

**Comment by MasterKeks** [comment]
@eldertek, Thank you for resolving the issue so quickly. Since the latest version, everything has been running smoothly for me, and I haven’t encountered any problems. It looks fantastic! I really appreciate your prompt support.

Wishing you a happy new year and all the best for the future. You have a really nice app here, helped me a lot. Keep up the great work!

Best regards,
MK
